-- Expand site_settings so (almost) all guest chrome is Table-Editor editable.
-- Safe to re-run. Existing columns kept. New cols get defaults from craft SSOT.

alter table public.site_settings
  add column if not exists brand_name text,
  add column if not exists brand_name_cn text,
  add column if not exists brand_short text,
  add column if not exists city text,
  add column if not exists seo_description text,
  add column if not exists seo_title_suffix text,
  add column if not exists mode_table_label text,
  add column if not exists mode_takeout_label text,
  add column if not exists action_directions text,
  add column if not exists action_call text,
  add column if not exists action_reserve text,
  add column if not exists action_reserve_nav text,
  add column if not exists visit_find_us text,
  add column if not exists visit_hours_label text,
  add column if not exists section_story_en text,
  add column if not exists section_story_cn text,
  add column if not exists section_menu_en text,
  add column if not exists section_menu_cn text,
  add column if not exists section_visit_en text,
  add column if not exists section_visit_cn text,
  add column if not exists story_chapters_aria text,
  add column if not exists dishes_aria text,
  add column if not exists nav_story text,
  add column if not exists nav_menu text,
  add column if not exists nav_visit text,
  add column if not exists nav_primary_aria text,
  add column if not exists menu_meta_house text,
  add column if not exists menu_meta_shellfish text,
  add column if not exists footer_tag text,
  add column if not exists footer_rights text,
  add column if not exists skip_to_menu text,
  add column if not exists skip_to_menu_href text,
  add column if not exists home_aria_suffix text,
  add column if not exists hours_timezone text,
  add column if not exists hours_note text,
  add column if not exists hours_closed_weekdays text,
  add column if not exists hours_periods jsonb,
  add column if not exists kitchen_open text,
  add column if not exists kitchen_until text,
  add column if not exists kitchen_opens text,
  add column if not exists kitchen_see_visit text,
  add column if not exists kitchen_closed_prefix text,
  add column if not exists kitchen_daily text,
  add column if not exists kitchen_eastern text,
  add column if not exists kitchen_title_open text,
  add column if not exists kitchen_title_closed text;

-- Seed craft defaults where null (do not overwrite non-null custom values)
update public.site_settings set
  brand_name = coalesce(brand_name, 'Zhe · The Fold'),
  brand_name_cn = coalesce(brand_name_cn, '褶'),
  brand_short = coalesce(brand_short, 'Zhe'),
  city = coalesce(city, 'New York City'),
  seo_description = coalesce(
    seo_description,
    'Handmade Chinese dumplings in New York. A small hybrid room for the table or takeout. Every fold holds the mark of a hand.'
  ),
  seo_title_suffix = coalesce(seo_title_suffix, 'Handmade Dumplings in New York'),
  mode_table_label = coalesce(mode_table_label, 'Table'),
  mode_takeout_label = coalesce(mode_takeout_label, 'Takeout'),
  action_directions = coalesce(action_directions, 'Directions'),
  action_call = coalesce(action_call, 'Call'),
  action_reserve = coalesce(action_reserve, 'Reserve'),
  action_reserve_nav = coalesce(action_reserve_nav, 'Reserve'),
  visit_find_us = coalesce(visit_find_us, 'Find us'),
  visit_hours_label = coalesce(visit_hours_label, 'Hours'),
  section_story_en = coalesce(section_story_en, 'The house'),
  section_story_cn = coalesce(section_story_cn, '小店'),
  section_menu_en = coalesce(section_menu_en, 'The Menu'),
  section_menu_cn = coalesce(section_menu_cn, '菜单'),
  section_visit_en = coalesce(section_visit_en, 'Visit'),
  section_visit_cn = coalesce(section_visit_cn, '造访'),
  story_chapters_aria = coalesce(story_chapters_aria, 'Story chapters'),
  dishes_aria = coalesce(dishes_aria, 'Dishes'),
  nav_story = coalesce(nav_story, 'Story'),
  nav_menu = coalesce(nav_menu, 'Menu'),
  nav_visit = coalesce(nav_visit, 'Visit'),
  nav_primary_aria = coalesce(nav_primary_aria, 'Primary'),
  menu_meta_house = coalesce(menu_meta_house, 'House'),
  menu_meta_shellfish = coalesce(menu_meta_shellfish, 'Shellfish'),
  footer_tag = coalesce(footer_tag, 'The imperfect pleats are the point'),
  footer_rights = coalesce(footer_rights, 'All rights reserved.'),
  skip_to_menu = coalesce(skip_to_menu, 'Skip to menu'),
  skip_to_menu_href = coalesce(skip_to_menu_href, '#menu'),
  home_aria_suffix = coalesce(home_aria_suffix, 'home'),
  hours_timezone = coalesce(hours_timezone, 'America/New_York'),
  hours_note = coalesce(hours_note, 'Closed Mondays'),
  hours_closed_weekdays = coalesce(hours_closed_weekdays, 'Mon'),
  hours_periods = coalesce(
    hours_periods,
    '[
      {"days":["Tue","Wed","Thu","Fri","Sat","Sun"],"open":"11:30","close":"14:30"},
      {"days":["Tue","Wed","Thu","Fri","Sat","Sun"],"open":"17:00","close":"21:00"}
    ]'::jsonb
  ),
  kitchen_open = coalesce(kitchen_open, 'Open'),
  kitchen_until = coalesce(kitchen_until, 'until'),
  kitchen_opens = coalesce(kitchen_opens, 'opens'),
  kitchen_see_visit = coalesce(kitchen_see_visit, 'see Visit'),
  kitchen_closed_prefix = coalesce(kitchen_closed_prefix, 'Closed'),
  kitchen_daily = coalesce(kitchen_daily, 'Daily'),
  kitchen_eastern = coalesce(kitchen_eastern, 'Eastern time'),
  kitchen_title_open = coalesce(kitchen_title_open, 'Kitchen open until'),
  kitchen_title_closed = coalesce(kitchen_title_closed, 'Kitchen'),
  updated_at = now()
where id = 'default';
